use super::*;

pub(crate) fn android_proot_current_group_ids() -> Vec<u64> {
    let Ok(status) = std::fs::read_to_string("/proc/self/status") else {
        return Vec::new();
    };
    let Some(groups) = status.lines().find(|line| line.starts_with("Groups:")) else {
        return Vec::new();
    };
    groups
        .trim_start_matches("Groups:")
        .split_whitespace()
        .filter_map(|item| item.parse::<u64>().ok())
        .collect()
}

pub(crate) fn android_proot_write_if_missing(path: &std::path::Path, content: &str) -> Result<(), String> {
    if path.is_file()
        && std::fs::read_to_string(path)
            .map(|text| !text.trim().is_empty())
            .unwrap_or(false)
    {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|err| format!("创建 Android rootfs 配置目录失败 ({}): {err}", parent.display()))?;
    }
    std::fs::write(path, content)
        .map_err(|err| format!("写入 Android rootfs 配置失败 ({}): {err}", path.display()))
}

pub(crate) fn android_proot_patch_resolv_conf(etc_dir: &std::path::Path) -> Result<(), String> {
    let path = etc_dir.join("resolv.conf");
    let should_write = match std::fs::symlink_metadata(&path) {
        Ok(metadata) if metadata.file_type().is_symlink() => true,
        Ok(metadata) if !metadata.is_file() => true,
        Ok(_) => std::fs::read_to_string(&path)
            .map(|text| {
                !text.lines().any(|line| {
                    let line = line.trim_start();
                    let Some(server) = line.strip_prefix("nameserver ") else {
                        return false;
                    };
                    let server = server.trim();
                    !matches!(server, "" | "127.0.0.1" | "127.0.0.53" | "::1")
                })
            })
            .unwrap_or(true),
        Err(_) => true,
    };
    if !should_write {
        return Ok(());
    }
    let _ = std::fs::remove_file(&path);
    std::fs::write(
        &path,
        "# Generated by P-AI Android workspace.\nnameserver 1.1.1.1\nnameserver 8.8.8.8\nnameserver 223.5.5.5\noptions edns0 trust-ad\n",
    )
    .map_err(|err| format!("写入 Android rootfs DNS 配置失败 ({}): {err}", path.display()))
}

pub(crate) fn android_proot_patch_group_file(etc_dir: &std::path::Path) -> Result<(), String> {
    let path = etc_dir.join("group");
    if !path.exists() {
        android_proot_write_if_missing(&path, "root:x:0:\n")?;
    }
    let mut text = std::fs::read_to_string(&path).unwrap_or_default();
    let existing_ids = text
        .lines()
        .filter_map(|line| line.split(':').nth(2)?.parse::<u64>().ok())
        .collect::<std::collections::HashSet<_>>();
    let mut additions = Vec::<String>::new();
    for group_id in android_proot_current_group_ids() {
        if group_id > 0 && !existing_ids.contains(&group_id) {
            additions.push(format!("android_gid_{group_id}:x:{group_id}:"));
        }
    }
    if additions.is_empty() {
        return Ok(());
    }
    if !text.ends_with('\n') {
        text.push('\n');
    }
    for line in additions {
        text.push_str(&line);
        text.push('\n');
    }
    std::fs::write(&path, text)
        .map_err(|err| format!("写入 Android rootfs group 配置失败 ({}): {err}", path.display()))
}

pub(crate) fn android_proot_set_path_mode(path: &std::path::Path, mode: u32) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode));
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        let _ = mode;
    }
}

pub(crate) fn android_proot_set_dir_mode(path: &std::path::Path, mode: u32) {
    android_proot_set_path_mode(path, mode);
}

pub(crate) fn android_proot_ensure_host_pai_layout(root: &std::path::Path) -> Result<(), String> {
    for relative in [
        ".pai",
        ".pai/plan",
        "skills",
        "private-organization",
        "mcp",
    ] {
        let dir = root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android 助理空间宿主映射目录失败 ({}): {err}", dir.display()))?;
    }
    Ok(())
}

pub(crate) fn android_proot_ensure_root_pai_layout(runtime_root: &std::path::Path) -> Result<(), String> {
    for relative in [
        "root/.pai",
        "root/.pai/skills",
        "root/.pai/private-organization",
        "root/.pai/mcp",
        "root/.pai/plan",
    ] {
        let dir = runtime_root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android rootfs 助理空间映射目录失败 ({}): {err}", dir.display()))?;
    }
    Ok(())
}

pub(crate) fn android_proot_rootfs_normalize_path(path: &std::path::Path) -> std::path::PathBuf {
    let mut normalized = std::path::PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            std::path::Component::RootDir => normalized.push(std::path::MAIN_SEPARATOR.to_string()),
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            std::path::Component::Normal(part) => normalized.push(part),
        }
    }
    normalized
}

pub(crate) fn android_proot_resolve_rootfs_symlink_target(
    runtime_root: &std::path::Path,
    link_path: &std::path::Path,
    link_target: &std::path::Path,
) -> Option<std::path::PathBuf> {
    let runtime_root = android_proot_rootfs_normalize_path(runtime_root);
    let link_path = android_proot_rootfs_normalize_path(link_path);
    let resolved = if link_target.is_absolute() {
        let mut target = runtime_root.clone();
        for component in link_target.components() {
            match component {
                std::path::Component::Normal(part) => target.push(part),
                std::path::Component::RootDir | std::path::Component::CurDir => {}
                std::path::Component::ParentDir => {
                    target.pop();
                }
                std::path::Component::Prefix(_) => return None,
            }
        }
        android_proot_rootfs_normalize_path(&target)
    } else {
        let parent = link_path.parent()?;
        android_proot_rootfs_normalize_path(&parent.join(link_target))
    };
    resolved.starts_with(&runtime_root).then_some(resolved)
}

pub(crate) fn android_proot_relative_rootfs_symlink_target(
    runtime_root: &std::path::Path,
    link_path: &std::path::Path,
    link_target: &std::path::Path,
) -> Option<String> {
    let runtime_root = android_proot_rootfs_normalize_path(runtime_root);
    let link_path = android_proot_rootfs_normalize_path(link_path);
    let parent = link_path.parent()?;
    let resolved = android_proot_resolve_rootfs_symlink_target(&runtime_root, &link_path, link_target)?;
    let from = parent.strip_prefix(&runtime_root).ok()?;
    let to = resolved.strip_prefix(&runtime_root).ok()?;
    let from_parts = from
        .components()
        .filter_map(|component| match component {
            std::path::Component::Normal(part) => Some(part.to_string_lossy().to_string()),
            _ => None,
        })
        .collect::<Vec<_>>();
    let to_parts = to
        .components()
        .filter_map(|component| match component {
            std::path::Component::Normal(part) => Some(part.to_string_lossy().to_string()),
            _ => None,
        })
        .collect::<Vec<_>>();
    let mut common = 0usize;
    while common < from_parts.len() && common < to_parts.len() && from_parts[common] == to_parts[common] {
        common += 1;
    }
    let mut relative = Vec::<String>::new();
    for _ in common..from_parts.len() {
        relative.push("..".to_string());
    }
    relative.extend(to_parts.into_iter().skip(common));
    Some(if relative.is_empty() { ".".to_string() } else { relative.join("/") })
}

pub(crate) fn android_proot_repair_rootfs_symlink_if_needed(
    runtime_root: &std::path::Path,
    relative_path: &str,
) -> Result<(), String> {
    let link_path = runtime_root.join(relative_path);
    let Ok(metadata) = std::fs::symlink_metadata(&link_path) else {
        return Ok(());
    };
    if !metadata.file_type().is_symlink() {
        return Ok(());
    }
    let link_target = std::fs::read_link(&link_path)
        .map_err(|err| format!("读取 Android Linux rootfs 符号链接失败 ({}): {err}", link_path.display()))?;
    if !link_target.is_absolute() {
        return Ok(());
    }
    let host_target = android_proot_relative_rootfs_symlink_target(runtime_root, &link_path, &link_target)
        .ok_or_else(|| format!("Android Linux rootfs 符号链接目标非法：{} -> {}", relative_path, link_target.display()))?;
    std::fs::remove_file(&link_path)
        .map_err(|err| format!("清理 Android Linux rootfs 符号链接失败 ({}): {err}", link_path.display()))?;
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink(std::path::Path::new(&host_target), &link_path)
            .map_err(|err| format!("修复 Android Linux rootfs 符号链接失败 ({} -> {}): {err}", relative_path, host_target))?;
    }
    #[cfg(not(unix))]
    {
        let _ = host_target;
    }
    Ok(())
}

pub(crate) fn android_proot_container_file_issue(
    runtime_root: &std::path::Path,
    relative_path: &str,
) -> Option<String> {
    let root = android_proot_rootfs_normalize_path(runtime_root);
    let path = android_proot_rootfs_normalize_path(&runtime_root.join(relative_path));
    if !path.starts_with(&root) {
        return Some("escapes rootfs".to_string());
    }
    android_proot_container_file_issue_inner(&root, &path, &mut std::collections::HashSet::new())
}

pub(crate) fn android_proot_container_file_issue_inner(
    runtime_root: &std::path::Path,
    path: &std::path::Path,
    visited: &mut std::collections::HashSet<std::path::PathBuf>,
) -> Option<String> {
    if !visited.insert(path.to_path_buf()) {
        return Some("symlink loop".to_string());
    }
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(_) => return Some("missing".to_string()),
    };
    if metadata.file_type().is_symlink() {
        let link_target = match std::fs::read_link(path) {
            Ok(target) => target,
            Err(_) => return Some("unreadable symlink".to_string()),
        };
        let resolved = match android_proot_resolve_rootfs_symlink_target(runtime_root, path, &link_target) {
            Some(path) => path,
            None => return Some("broken symlink".to_string()),
        };
        return android_proot_container_file_issue_inner(runtime_root, &resolved, visited);
    }
    if !metadata.is_file() {
        return Some("not a file".to_string());
    }
    if metadata.len() == 0 {
        return Some("empty file".to_string());
    }
    None
}

pub(crate) fn android_proot_replace_with_file_copy(
    source: &std::path::Path,
    target: &std::path::Path,
    context: &str,
) -> Result<(), String> {
    if let Ok(metadata) = std::fs::symlink_metadata(target) {
        if metadata.is_dir() && !metadata.file_type().is_symlink() {
            std::fs::remove_dir_all(target)
                .map_err(|err| format!("清理 Android Linux rootfs 入口目录失败 ({context}, {}): {err}", target.display()))?;
        } else {
            std::fs::remove_file(target)
                .map_err(|err| format!("清理 Android Linux rootfs 入口失败 ({context}, {}): {err}", target.display()))?;
        }
    }
    std::fs::copy(source, target)
        .map_err(|err| format!("补齐 Android Linux rootfs 入口失败 ({context}, {} -> {}): {err}", source.display(), target.display()))?;
    android_proot_set_path_mode(target, 0o755);
    Ok(())
}

pub(crate) fn android_proot_ensure_rootfs_entrypoints(runtime_root: &std::path::Path) -> Result<(), String> {
    for relative in ["bin", "sbin", "lib", "lib64"] {
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, relative)?;
    }

    let dash = runtime_root.join("usr").join("bin").join("dash");
    if let Some(issue) = android_proot_container_file_issue(runtime_root, "usr/bin/dash") {
        return Err(format!(
            "Android Linux rootfs 缺少可用 usr/bin/dash：issue={} path={}",
            issue,
            dash.display()
        ));
    }

    // Ubuntu base 的 /bin 通常是指向 /usr/bin 的 symlink；proot 解析 /bin/sh 后
    // 实际 execve /usr/bin/sh，因此两个入口都必须可用。
    let usr_bin_dir = runtime_root.join("usr").join("bin");
    std::fs::create_dir_all(&usr_bin_dir)
        .map_err(|err| format!("创建 Android Linux rootfs usr/bin 目录失败 ({}): {err}", usr_bin_dir.display()))?;
    for relative in ["usr/bin/sh", "usr/bin/env"] {
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, relative)?;
    }
    let usr_sh = usr_bin_dir.join("sh");
    if android_proot_container_file_issue(runtime_root, "usr/bin/sh").is_some() {
        android_proot_replace_with_file_copy(&dash, &usr_sh, "/usr/bin/sh")?;
    } else {
        android_proot_set_path_mode(&usr_sh, 0o755);
    }

    let bin_dir = runtime_root.join("bin");
    let bin_is_symlink = std::fs::symlink_metadata(&bin_dir)
        .map(|metadata| metadata.file_type().is_symlink())
        .unwrap_or(false);
    if !bin_is_symlink {
        std::fs::create_dir_all(&bin_dir)
            .map_err(|err| format!("创建 Android Linux rootfs bin 目录失败 ({}): {err}", bin_dir.display()))?;
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, "bin/sh")?;
        let sh = bin_dir.join("sh");
        if android_proot_container_file_issue(runtime_root, "bin/sh").is_some() {
            android_proot_replace_with_file_copy(&dash, &sh, "/bin/sh")?;
        } else {
            android_proot_set_path_mode(&sh, 0o755);
        }
    }
    Ok(())
}

pub(crate) fn android_proot_patch_rootfs(runtime_root: &std::path::Path) -> Result<(), String> {
    android_proot_ensure_rootfs_entrypoints(runtime_root)?;
    android_proot_ensure_root_pai_layout(runtime_root)?;
    let etc_dir = runtime_root.join("etc");
    if !etc_dir.is_dir() {
        return Ok(());
    }
    android_proot_patch_resolv_conf(&etc_dir)?;
    android_proot_write_if_missing(&etc_dir.join("hosts"), "127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")?;
    android_proot_write_if_missing(&etc_dir.join("hostname"), "localhost\n")?;
    let default_dir = etc_dir.join("default");
    std::fs::create_dir_all(&default_dir)
        .map_err(|err| format!("创建 Android rootfs locale 目录失败 ({}): {err}", default_dir.display()))?;
    android_proot_write_if_missing(&default_dir.join("locale"), "LANG=C.UTF-8\n")?;
    android_proot_patch_group_file(&etc_dir)?;

    for relative in ["tmp", "var/tmp", "root"] {
        let dir = runtime_root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android rootfs 运行目录失败 ({}): {err}", dir.display()))?;
        if matches!(relative, "tmp" | "var/tmp") {
            android_proot_set_dir_mode(&dir, 0o1777);
        } else {
            android_proot_set_dir_mode(&dir, 0o700);
        }
    }
    Ok(())
}
