#[cfg(target_os = "android")]
const ANDROID_PROOT_EXEC: &str = "libproot_exec.so";
#[cfg(target_os = "android")]
const ANDROID_PROOT_LOADER: &str = "libproot_loader.so";
#[cfg(target_os = "android")]
const ANDROID_PROOT_REQUIRED_LIBS: &[&str] = &["libtalloc.so", "libandroid-shmem.so"];
#[cfg(target_os = "android")]
const ANDROID_PROOT_TALLOC_COMPAT_LIB: &str = "libtalloc.so.2";
#[cfg(target_os = "android")]
const ANDROID_PROOT_WORKSPACE_DIR: &str = "/workspace";
#[cfg(target_os = "android")]
const ANDROID_PROOT_ASSISTANT_SPACE_DIR: &str = "/root/.pai";

#[cfg(target_os = "android")]
fn android_proot_candidate_dirs() -> Vec<std::path::PathBuf> {
    let mut out = Vec::<std::path::PathBuf>::new();
    let mut seen = std::collections::HashSet::<String>::new();
    let mut push = |path: std::path::PathBuf| {
        if !path.is_dir() {
            return;
        }
        let key = path.to_string_lossy().to_string();
        if seen.insert(key) {
            out.push(path);
        }
    };

    if let Ok(paths) = std::env::var("LD_LIBRARY_PATH") {
        for raw in paths.split(':') {
            let trimmed = raw.trim();
            if !trimmed.is_empty() {
                push(std::path::PathBuf::from(trimmed));
            }
        }
    }

    if let Ok(maps) = std::fs::read_to_string("/proc/self/maps") {
        for token in maps.split_whitespace() {
            if !token.ends_with(".so") {
                continue;
            }
            let path = std::path::PathBuf::from(token);
            let Some(file_name) = path.file_name().and_then(|value| value.to_str()) else {
                continue;
            };
            if matches!(file_name, "libeasy_call_ai_lib.so" | "libtauri_app.so") || file_name.starts_with("libeasy_call") {
                if let Some(parent) = path.parent() {
                    push(parent.to_path_buf());
                }
            }
        }
    }

    out
}

#[cfg(target_os = "android")]
fn android_proot_binary_paths() -> Result<(std::path::PathBuf, std::path::PathBuf, Option<std::path::PathBuf>), String> {
    let candidates = android_proot_candidate_dirs();
    for dir in &candidates {
        let proot = dir.join(ANDROID_PROOT_EXEC);
        if proot.is_file() {
            let loader = dir.join(ANDROID_PROOT_LOADER);
            let loader = if loader.is_file() { Some(loader) } else { None };
            return Ok((dir.clone(), proot, loader));
        }
    }
    let searched = candidates
        .iter()
        .map(|path| path.to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    Err(format!(
        "Android Linux 执行层缺失：未找到 {ANDROID_PROOT_EXEC}。请把合法来源的 proot native libs 放入 src-tauri/android/jniLibs/<abi>/ 后重新打包。已搜索：{}",
        if searched.is_empty() { "无候选 nativeLibraryDir" } else { searched.as_str() }
    ))
}

#[cfg(target_os = "android")]
fn android_proot_current_group_ids() -> Vec<u64> {
    let Ok(status) = std::fs::read_to_string("/proc/self/status") else {
        return Vec::new();
    };
    let Some(groups) = status.lines().find(|line| line.starts_with("Groups:")) else {
        return Vec::new();
    };
    groups
        .trim_start_matches("Groups:")
        .split_whitespace()
        .filter_map(|item| item.parse::<u64>().ok())
        .collect()
}

#[cfg(target_os = "android")]
fn android_proot_write_if_missing(path: &std::path::Path, content: &str) -> Result<(), String> {
    if path.is_file()
        && std::fs::read_to_string(path)
            .map(|text| !text.trim().is_empty())
            .unwrap_or(false)
    {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|err| format!("创建 Android rootfs 配置目录失败 ({}): {err}", parent.display()))?;
    }
    std::fs::write(path, content)
        .map_err(|err| format!("写入 Android rootfs 配置失败 ({}): {err}", path.display()))
}

#[cfg(target_os = "android")]
fn android_proot_patch_resolv_conf(etc_dir: &std::path::Path) -> Result<(), String> {
    let path = etc_dir.join("resolv.conf");
    let should_write = match std::fs::symlink_metadata(&path) {
        Ok(metadata) if metadata.file_type().is_symlink() => true,
        Ok(metadata) if !metadata.is_file() => true,
        Ok(_) => std::fs::read_to_string(&path)
            .map(|text| {
                !text.lines().any(|line| {
                    let line = line.trim_start();
                    let Some(server) = line.strip_prefix("nameserver ") else {
                        return false;
                    };
                    let server = server.trim();
                    !matches!(server, "" | "127.0.0.1" | "127.0.0.53" | "::1")
                })
            })
            .unwrap_or(true),
        Err(_) => true,
    };
    if !should_write {
        return Ok(());
    }
    let _ = std::fs::remove_file(&path);
    std::fs::write(
        &path,
        "# Generated by P-AI Android workspace.\nnameserver 1.1.1.1\nnameserver 8.8.8.8\nnameserver 223.5.5.5\noptions edns0 trust-ad\n",
    )
    .map_err(|err| format!("写入 Android rootfs DNS 配置失败 ({}): {err}", path.display()))
}

#[cfg(target_os = "android")]
fn android_proot_patch_group_file(etc_dir: &std::path::Path) -> Result<(), String> {
    let path = etc_dir.join("group");
    if !path.exists() {
        android_proot_write_if_missing(&path, "root:x:0:\n")?;
    }
    let mut text = std::fs::read_to_string(&path).unwrap_or_default();
    let existing_ids = text
        .lines()
        .filter_map(|line| line.split(':').nth(2)?.parse::<u64>().ok())
        .collect::<std::collections::HashSet<_>>();
    let mut additions = Vec::<String>::new();
    for group_id in android_proot_current_group_ids() {
        if group_id > 0 && !existing_ids.contains(&group_id) {
            additions.push(format!("android_gid_{group_id}:x:{group_id}:"));
        }
    }
    if additions.is_empty() {
        return Ok(());
    }
    if !text.ends_with('\n') {
        text.push('\n');
    }
    for line in additions {
        text.push_str(&line);
        text.push('\n');
    }
    std::fs::write(&path, text)
        .map_err(|err| format!("写入 Android rootfs group 配置失败 ({}): {err}", path.display()))
}

#[cfg(target_os = "android")]
fn android_proot_set_path_mode(path: &std::path::Path, mode: u32) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode));
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        let _ = mode;
    }
}

#[cfg(target_os = "android")]
fn android_proot_set_dir_mode(path: &std::path::Path, mode: u32) {
    android_proot_set_path_mode(path, mode);
}

#[cfg(target_os = "android")]
fn android_proot_ensure_host_pai_layout(root: &std::path::Path) -> Result<(), String> {
    for relative in [
        ".pai",
        ".pai/skills",
        ".pai/private-organization",
        ".pai/mcp",
        ".pai/plan",
    ] {
        let dir = root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android 助理空间宿主映射目录失败 ({}): {err}", dir.display()))?;
    }
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_ensure_root_pai_layout(runtime_root: &std::path::Path) -> Result<(), String> {
    for relative in [
        "root/.pai",
        "root/.pai/skills",
        "root/.pai/private-organization",
        "root/.pai/mcp",
        "root/.pai/plan",
    ] {
        let dir = runtime_root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android rootfs 助理空间映射目录失败 ({}): {err}", dir.display()))?;
    }
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_ensure_libs_dir(native_dir: &std::path::Path, temp_dir: &std::path::Path) -> Result<std::path::PathBuf, String> {
    let libs_dir = temp_dir.join("libs");
    std::fs::create_dir_all(&libs_dir)
        .map_err(|err| format!("创建 Android proot 库目录失败 ({}): {err}", libs_dir.display()))?;
    let mut missing = Vec::<String>::new();
    for lib_name in ANDROID_PROOT_REQUIRED_LIBS {
        let target = libs_dir.join(lib_name);
        if target.is_file() {
            continue;
        }
        let direct_source = native_dir.join(lib_name);
        let source = if direct_source.is_file() {
            Some(direct_source)
        } else if *lib_name == "libtalloc.so" {
            let compat_source = native_dir.join(ANDROID_PROOT_TALLOC_COMPAT_LIB);
            compat_source.is_file().then_some(compat_source)
        } else {
            None
        };
        if let Some(src) = source {
            std::fs::copy(&src, &target)
                .map_err(|err| format!("复制 Android proot 依赖库失败 ({} -> {}): {err}", src.display(), target.display()))?;
            continue;
        }
        missing.push((*lib_name).to_string());
    }
    if !missing.is_empty() {
        return Err(format!(
            "Android proot 依赖库缺失：missing={}，native_dir={}。请确认 APK 已打包 libtalloc.so 和 libandroid-shmem.so，且 proot 的 NEEDED 已从 libtalloc.so.2 修补为 libtalloc.so。",
            missing.join(","),
            native_dir.display()
        ));
    }
    Ok(libs_dir)
}

#[cfg(target_os = "android")]
fn android_proot_rootfs_normalize_path(path: &std::path::Path) -> std::path::PathBuf {
    let mut normalized = std::path::PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            std::path::Component::RootDir => normalized.push(std::path::MAIN_SEPARATOR.to_string()),
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            std::path::Component::Normal(part) => normalized.push(part),
        }
    }
    normalized
}

#[cfg(target_os = "android")]
fn android_proot_resolve_rootfs_symlink_target(
    runtime_root: &std::path::Path,
    link_path: &std::path::Path,
    link_target: &std::path::Path,
) -> Option<std::path::PathBuf> {
    let runtime_root = android_proot_rootfs_normalize_path(runtime_root);
    let link_path = android_proot_rootfs_normalize_path(link_path);
    let resolved = if link_target.is_absolute() {
        let mut target = runtime_root.clone();
        for component in link_target.components() {
            match component {
                std::path::Component::Normal(part) => target.push(part),
                std::path::Component::RootDir | std::path::Component::CurDir => {}
                std::path::Component::ParentDir => {
                    target.pop();
                }
                std::path::Component::Prefix(_) => return None,
            }
        }
        android_proot_rootfs_normalize_path(&target)
    } else {
        let parent = link_path.parent()?;
        android_proot_rootfs_normalize_path(&parent.join(link_target))
    };
    resolved.starts_with(&runtime_root).then_some(resolved)
}

#[cfg(target_os = "android")]
fn android_proot_relative_rootfs_symlink_target(
    runtime_root: &std::path::Path,
    link_path: &std::path::Path,
    link_target: &std::path::Path,
) -> Option<String> {
    let runtime_root = android_proot_rootfs_normalize_path(runtime_root);
    let link_path = android_proot_rootfs_normalize_path(link_path);
    let parent = link_path.parent()?;
    let resolved = android_proot_resolve_rootfs_symlink_target(&runtime_root, &link_path, link_target)?;
    let from = parent.strip_prefix(&runtime_root).ok()?;
    let to = resolved.strip_prefix(&runtime_root).ok()?;
    let from_parts = from
        .components()
        .filter_map(|component| match component {
            std::path::Component::Normal(part) => Some(part.to_string_lossy().to_string()),
            _ => None,
        })
        .collect::<Vec<_>>();
    let to_parts = to
        .components()
        .filter_map(|component| match component {
            std::path::Component::Normal(part) => Some(part.to_string_lossy().to_string()),
            _ => None,
        })
        .collect::<Vec<_>>();
    let mut common = 0usize;
    while common < from_parts.len() && common < to_parts.len() && from_parts[common] == to_parts[common] {
        common += 1;
    }
    let mut relative = Vec::<String>::new();
    for _ in common..from_parts.len() {
        relative.push("..".to_string());
    }
    relative.extend(to_parts.into_iter().skip(common));
    Some(if relative.is_empty() { ".".to_string() } else { relative.join("/") })
}

#[cfg(target_os = "android")]
fn android_proot_repair_rootfs_symlink_if_needed(
    runtime_root: &std::path::Path,
    relative_path: &str,
) -> Result<(), String> {
    let link_path = runtime_root.join(relative_path);
    let Ok(metadata) = std::fs::symlink_metadata(&link_path) else {
        return Ok(());
    };
    if !metadata.file_type().is_symlink() {
        return Ok(());
    }
    let link_target = std::fs::read_link(&link_path)
        .map_err(|err| format!("读取 Android Linux rootfs 符号链接失败 ({}): {err}", link_path.display()))?;
    if !link_target.is_absolute() {
        return Ok(());
    }
    let host_target = android_proot_relative_rootfs_symlink_target(runtime_root, &link_path, &link_target)
        .ok_or_else(|| format!("Android Linux rootfs 符号链接目标非法：{} -> {}", relative_path, link_target.display()))?;
    std::fs::remove_file(&link_path)
        .map_err(|err| format!("清理 Android Linux rootfs 符号链接失败 ({}): {err}", link_path.display()))?;
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink(std::path::Path::new(&host_target), &link_path)
            .map_err(|err| format!("修复 Android Linux rootfs 符号链接失败 ({} -> {}): {err}", relative_path, host_target))?;
    }
    #[cfg(not(unix))]
    {
        let _ = host_target;
    }
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_container_file_issue(
    runtime_root: &std::path::Path,
    relative_path: &str,
) -> Option<String> {
    let root = android_proot_rootfs_normalize_path(runtime_root);
    let path = android_proot_rootfs_normalize_path(&runtime_root.join(relative_path));
    if !path.starts_with(&root) {
        return Some("escapes rootfs".to_string());
    }
    android_proot_container_file_issue_inner(&root, &path, &mut std::collections::HashSet::new())
}

#[cfg(target_os = "android")]
fn android_proot_container_file_issue_inner(
    runtime_root: &std::path::Path,
    path: &std::path::Path,
    visited: &mut std::collections::HashSet<std::path::PathBuf>,
) -> Option<String> {
    if !visited.insert(path.to_path_buf()) {
        return Some("symlink loop".to_string());
    }
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(_) => return Some("missing".to_string()),
    };
    if metadata.file_type().is_symlink() {
        let link_target = match std::fs::read_link(path) {
            Ok(target) => target,
            Err(_) => return Some("unreadable symlink".to_string()),
        };
        let resolved = match android_proot_resolve_rootfs_symlink_target(runtime_root, path, &link_target) {
            Some(path) => path,
            None => return Some("broken symlink".to_string()),
        };
        return android_proot_container_file_issue_inner(runtime_root, &resolved, visited);
    }
    if !metadata.is_file() {
        return Some("not a file".to_string());
    }
    if metadata.len() == 0 {
        return Some("empty file".to_string());
    }
    None
}

#[cfg(target_os = "android")]
fn android_proot_replace_with_file_copy(
    source: &std::path::Path,
    target: &std::path::Path,
    context: &str,
) -> Result<(), String> {
    if let Ok(metadata) = std::fs::symlink_metadata(target) {
        if metadata.is_dir() && !metadata.file_type().is_symlink() {
            std::fs::remove_dir_all(target)
                .map_err(|err| format!("清理 Android Linux rootfs 入口目录失败 ({context}, {}): {err}", target.display()))?;
        } else {
            std::fs::remove_file(target)
                .map_err(|err| format!("清理 Android Linux rootfs 入口失败 ({context}, {}): {err}", target.display()))?;
        }
    }
    std::fs::copy(source, target)
        .map_err(|err| format!("补齐 Android Linux rootfs 入口失败 ({context}, {} -> {}): {err}", source.display(), target.display()))?;
    android_proot_set_path_mode(target, 0o755);
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_ensure_rootfs_entrypoints(runtime_root: &std::path::Path) -> Result<(), String> {
    for relative in ["bin", "sbin", "lib", "lib64"] {
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, relative)?;
    }

    let dash = runtime_root.join("usr").join("bin").join("dash");
    if let Some(issue) = android_proot_container_file_issue(runtime_root, "usr/bin/dash") {
        return Err(format!(
            "Android Linux rootfs 缺少可用 usr/bin/dash：issue={} path={}",
            issue,
            dash.display()
        ));
    }

    let bin_dir = runtime_root.join("bin");
    let bin_is_symlink = std::fs::symlink_metadata(&bin_dir)
        .map(|metadata| metadata.file_type().is_symlink())
        .unwrap_or(false);
    if !bin_is_symlink {
        std::fs::create_dir_all(&bin_dir)
            .map_err(|err| format!("创建 Android Linux rootfs bin 目录失败 ({}): {err}", bin_dir.display()))?;
    }

    for relative in ["usr/bin/sh", "usr/bin/env"] {
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, relative)?;
    }
    if !bin_is_symlink {
        android_proot_repair_rootfs_symlink_if_needed(runtime_root, "bin/sh")?;
    }

    let sh = bin_dir.join("sh");
    if android_proot_container_file_issue(runtime_root, "bin/sh").is_some() {
        android_proot_replace_with_file_copy(&dash, &sh, "/bin/sh")?;
    } else {
        android_proot_set_path_mode(&sh, 0o755);
    }
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_patch_rootfs(runtime_root: &std::path::Path) -> Result<(), String> {
    android_proot_ensure_rootfs_entrypoints(runtime_root)?;
    android_proot_ensure_root_pai_layout(runtime_root)?;
    let etc_dir = runtime_root.join("etc");
    if !etc_dir.is_dir() {
        return Ok(());
    }
    android_proot_patch_resolv_conf(&etc_dir)?;
    android_proot_write_if_missing(&etc_dir.join("hosts"), "127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")?;
    android_proot_write_if_missing(&etc_dir.join("hostname"), "localhost\n")?;
    let default_dir = etc_dir.join("default");
    std::fs::create_dir_all(&default_dir)
        .map_err(|err| format!("创建 Android rootfs locale 目录失败 ({}): {err}", default_dir.display()))?;
    android_proot_write_if_missing(&default_dir.join("locale"), "LANG=C.UTF-8\n")?;
    android_proot_patch_group_file(&etc_dir)?;

    for relative in ["tmp", "var/tmp", "root"] {
        let dir = runtime_root.join(relative);
        std::fs::create_dir_all(&dir)
            .map_err(|err| format!("创建 Android rootfs 运行目录失败 ({}): {err}", dir.display()))?;
        if matches!(relative, "tmp" | "var/tmp") {
            android_proot_set_dir_mode(&dir, 0o1777);
        } else {
            android_proot_set_dir_mode(&dir, 0o700);
        }
    }
    Ok(())
}

#[cfg(target_os = "android")]
fn android_proot_workspace_cwd(root: &std::path::Path, cwd: &std::path::Path) -> Result<String, String> {
    let normalized = terminal_normalize_for_access_check(cwd);
    if !path_is_within(root, &normalized) {
        return Err(format!("Android Linux 命令工作目录不在沙盒内：{}", cwd.display()));
    }
    let relative = normalized
        .strip_prefix(root)
        .map_err(|_| format!("Android Linux 命令无法解析沙盒相对目录：{}", cwd.display()))?;
    let relative_text = relative.to_string_lossy().replace('\\', "/");
    if relative_text.trim().is_empty() {
        Ok(ANDROID_PROOT_WORKSPACE_DIR.to_string())
    } else {
        Ok(format!("{}/{}", ANDROID_PROOT_WORKSPACE_DIR, relative_text.trim_matches('/')))
    }
}

#[cfg(target_os = "android")]
fn android_proot_shell_args(runtime_root: &std::path::Path) -> (&'static str, Vec<&'static str>) {
    if runtime_root.join("bin").join("bash").is_file()
        || runtime_root.join("usr").join("bin").join("bash").is_file()
    {
        ("/bin/bash", vec!["-l", "-c"])
    } else {
        ("/bin/sh", vec!["-c"])
    }
}

#[cfg(target_os = "android")]
async fn sandbox_run_with_android_proot_backend(
    request: &SandboxRequest,
    state: &AppState,
) -> Result<SandboxExecutionResult, String> {
    let root = android_workspace_canonical_root_if_ready(state)?
        .ok_or_else(|| ANDROID_WORKSPACE_NOT_READY_MESSAGE.to_string())?;
    let runtime_root = android_workspace_runtime_root(&root);
    if !android_workspace_runtime_ready(&root) {
        return Err(ANDROID_WORKSPACE_NOT_READY_MESSAGE.to_string());
    }
    let temp_dir = root.join("tmp").join("proot");
    std::fs::create_dir_all(&temp_dir)
        .map_err(|err| format!("创建 Android proot 临时目录失败 ({}): {err}", temp_dir.display()))?;
    let hidden_workspace_dir = temp_dir.join("workspace-hidden");
    let hidden_runtime_dir = hidden_workspace_dir.join("runtime");
    let hidden_proot_tmp_dir = hidden_workspace_dir.join("tmp").join("proot");
    for dir in [&hidden_runtime_dir, &hidden_proot_tmp_dir] {
        std::fs::create_dir_all(dir)
            .map_err(|err| format!("创建 Android proot 工作区遮罩目录失败 ({}): {err}", dir.display()))?;
    }
    android_proot_ensure_host_pai_layout(&root)?;
    android_proot_patch_rootfs(&runtime_root)?;

    let (native_dir, proot, loader) = android_proot_binary_paths()?;
    let libs_dir = android_proot_ensure_libs_dir(&native_dir, &temp_dir)?;
    let proot_cwd = android_proot_workspace_cwd(&root, &request.cwd)?;
    let (shell_path, shell_args) = android_proot_shell_args(&runtime_root);

    let mut command_builder = tokio::process::Command::new(&proot);
    command_builder.kill_on_drop(true);
    command_builder.current_dir(&root);
    command_builder.stdout(std::process::Stdio::piped());
    command_builder.stderr(std::process::Stdio::piped());
    command_builder.stdin(std::process::Stdio::null());
    command_builder.env_clear();
    let ld_library_path = format!("{}:{}", libs_dir.display(), native_dir.display());
    command_builder.env("LD_LIBRARY_PATH", ld_library_path);
    if let Some(loader) = &loader {
        command_builder.env("PROOT_LOADER", loader);
    }
    command_builder.env("PROOT_TMP_DIR", &temp_dir);
    command_builder.env("TMPDIR", "/tmp");
    command_builder.env("HOME", "/root");
    command_builder.env("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin");
    command_builder.env("TERM", "xterm-256color");
    command_builder.env("LANG", "C.UTF-8");
    command_builder.env("LC_ALL", "C.UTF-8");
    command_builder.env("USER", "root");
    command_builder.env("SHELL", shell_path);
    command_builder.env("PAI_WORKSPACE", ANDROID_PROOT_WORKSPACE_DIR);
    command_builder.env("PAI_ASSISTANT_SPACE", ANDROID_PROOT_ASSISTANT_SPACE_DIR);
    command_builder.env("PAI_SKILLS_DIR", "/root/.pai/skills");

    command_builder.arg("--root-id");
    command_builder.arg("--link2symlink");
    command_builder.arg("--kill-on-exit");
    command_builder.arg("-r");
    command_builder.arg(&runtime_root);
    command_builder.arg("-w");
    command_builder.arg(&proot_cwd);
    command_builder.arg("-b");
    command_builder.arg(format!("{}:{ANDROID_PROOT_WORKSPACE_DIR}", root.display()));
    command_builder.arg("-b");
    command_builder.arg(format!("{}:{ANDROID_PROOT_WORKSPACE_DIR}/runtime", hidden_runtime_dir.display()));
    command_builder.arg("-b");
    command_builder.arg(format!("{}:{ANDROID_PROOT_WORKSPACE_DIR}/tmp/proot", hidden_proot_tmp_dir.display()));
    for (host, guest) in [
        (root.join(".pai"), ANDROID_PROOT_ASSISTANT_SPACE_DIR),
        (root.join("skills"), "/root/.pai/skills"),
        (root.join("private-organization"), "/root/.pai/private-organization"),
        (root.join("mcp"), "/root/.pai/mcp"),
    ] {
        if host.exists() {
            command_builder.arg("-b");
            command_builder.arg(format!("{}:{guest}", host.display()));
        }
    }
    for path in ["/dev", "/proc", "/sys"] {
        if std::path::Path::new(path).exists() {
            command_builder.arg("-b");
            command_builder.arg(path);
        }
    }

    command_builder.arg(shell_path);
    for arg in shell_args {
        command_builder.arg(arg);
    }
    command_builder.arg("unset LD_LIBRARY_PATH; cd -- \"$1\" && eval \"$2\"");
    command_builder.arg("pai-android");
    command_builder.arg(&proot_cwd);
    command_builder.arg(&request.command);

    let timeout_ms = request.timeout_ms.max(1);
    let started = std::time::Instant::now();
    let output = tokio::time::timeout(
        std::time::Duration::from_millis(timeout_ms),
        command_builder.output(),
    )
    .await
    .map_err(|_| format!("terminal_exec timed out after {}ms", timeout_ms))?
    .map_err(|err| format!("terminal_exec android proot spawn failed: {err}"))?;

    let duration_ms = started.elapsed().as_millis().min(u64::MAX as u128) as u64;
    let exit_code = output.status.code().unwrap_or(-1);
    Ok(SandboxExecutionResult {
        ok: output.status.success(),
        exit_code,
        stdout: output.stdout,
        stderr: output.stderr,
        duration_ms,
        shell_kind: "android-proot".to_string(),
        shell_path: format!("{} via {}", shell_path, proot.to_string_lossy()),
    })
}
